### ISSUE TITLE
Review metadata

### ISSUE THREAD

**Issue by ausi** [trakkedio/wordpress-connector#1]
@Toflar Please check if the metadata for the plugin is correct: https://github.com/trakkedio/wordpress-connector/blob/c922385cd3a1b2b07000a2d270205dee5f0bc59c/trakked-connector.php#L9-L14

And also the DocComment: https://github.com/trakkedio/wordpress-connector/blob/c922385cd3a1b2b07000a2d270205dee5f0bc59c/trakked-connector.php#L3-L6

**Comment by Toflar** [comment]
See https://github.com/trakkedio/wordpress-connector/pull/2
